### ISSUE TITLE
theta disconnects

### ISSUE THREAD

**Issue by CharlotteTorres** [buildwiththeta/buildwiththeta#105]
# **Title:** 

theta disconnects

## **Description:** 

after a while that you don't use theta it disconnects and shows a screen with the error

---

## **Flutter Environment:** 

.

## **App Version:** 

any close version

## **Device Information:** 

macOS ventura 13.4
---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. 
2. 
3. 
4. 

## **Expected Behavior:** 

.

## **Actual Behavior:** 

The screen shows the error

## **Logs:** 

.

## **Screenshots:**
<img width="1680" alt="Screenshot 2023-06-08 alle 00 33 40" src="https://github.com/buildwiththeta/buildwiththeta/assets/82865755/6d48b07f-07ad-4290-95f1-363384ee5ac5">

## **Additional Context:** 

.

## **Possible Solution:** 

.

---

Remember, providing as much detail as possible will make it easier for others to help you resolve the bug. If the bug is not immediately reproducible, it may be necessary to provide more context or a sample code snippet that demonstrates the issue.

**Comment by kasapiniz** [comment]
This bug was fixed in the previous update. Fix/bug fix general https://github.com/buildwiththeta/theta_studio/pull/68
