### ISSUE TITLE
Container size disappears

### ISSUE THREAD

**Issue by dariowskii** [buildwiththeta/buildwiththeta#110]
# **Title:** 

The size of the container disappears when placed inside a column.

## **Description:** 

The size of the container disappears when placed inside a column.

---

## **App Version:** 

Production app ([buildwiththeta](https://app.buildwiththeta.com/))

## **Device Information:** 

macOS 13.4 (22F66)
Browser: Google Chrome

---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. Create two separate containers with fixed sizes.
2. Insert a column widget inside one of two container
3. Insert other container inside the column.

## **Expected Behavior:** 

I expect the newly inserted container to maintain the same dimensions previously indicated.

## **Actual Behavior:** 

The size of the inserted container is resetted.

## **Screenshots:**

https://github.com/buildwiththeta/buildwiththeta/assets/62183044/e37cee00-3901-4390-a49a-91a47f1a8deb

**Comment by andreabuttarelli** [comment]
Duplicated #101
