### ISSUE TITLE
Container overflow

### ISSUE THREAD

**Issue by dariowskii** [buildwiththeta/buildwiththeta#111]
# **Title:** 

Container width and height render overflow error.

## **Description:** 

Inserting a column inside a container, with inside widgets larger than the parent container, a rendering overflow error occurs.

---

## **App Version:** 

Production app ([buildwiththeta](https://app.buildwiththeta.com/))

## **Device Information:** 

macOS 13.4 (22F66)
Browser: Google Chrome

---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. Create a container with full width and height of 80.
2. Put a column inside.
3. Put two containers of 52x52.

## **Expected Behavior:** 

I expect the container size to grow with the content or to get clipped.

## **Actual Behavior:** 

There is currently a render overflow.

## **Screenshots:**

<img width="1439" alt="Screenshot 2023-06-09 alle 17 39 14" src="https://github.com/buildwiththeta/buildwiththeta/assets/62183044/46521ee0-d3e8-4284-95a6-a4c3178b57cb">

**Comment by andreabuttarelli** [comment]
Hello!
After carefully analyzing it, I think this is not a real issue. In fact it is that the error you see was made ad hoc to trace that of Flutter in debug mode. 

I think the error is necessary if the user tries to exceed the parent size limits, which can be circumvented now with the introduction of the Collection widget that allows for scrollable areas.

**Comment by dariowskii** [comment]
Ok, I understand this point of view 👍🏻
Effectively, with the introduction of `Collection`, the rendering overflow shown here as an example no longer occurs.

Let's go 🚀
