### ISSUE TITLE
Text: Placeholder, fill and function to go to the next line.

### ISSUE THREAD

**Issue by gianlucadottaviotheta** [buildwiththeta/buildwiththeta#159]
### Contact Details

gianluca@buildwiththeta.com

### Feature

1- The copied text does not fill the "placeholder" text area.
Now I need to select the number of lines in the "max lines" section, but I expected it to be done automatically. Also, because I cannot know how many lines I need for the copied text.

2- Within the text field in the Node section, if I go to a new line in the entered text (by pressing "enter"), it treats it as a completion. The same thing happens if I press shift + enter.

https://github.com/buildwiththeta/buildwiththeta/assets/91491171/c23c02f8-39e9-43d5-9233-ea1346bad60a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreabuttarelli** [comment]
Hi @kasapiniz let’s add an empty value to maxLines for Texts
