### ISSUE TITLE
[Bug]: Is not updated when you move the order of the widgets

### ISSUE THREAD

**Issue by CharlotteTorres** [buildwiththeta/buildwiththeta#185]
### Product

Theta Studio

### Bug

if I change the order of two texts it is done at the moment but if I reload the page they return to the initial position 

### Device Information

macOs Ventura 13.4.1

### Steps to reproduce

1. insert two texts in a column
2. change the order

### Expected Behaviour

texts remain in the new order 

### Actual Behaviour

texts change order but as soon as you reload the page they return to the initial order

### Screenshots

Uploading Registrazione schermo 2023-07-07 alle 11.55.19.mov…

### Code of Conduct

- [X] I agree to follow the Code of Conduct for this project.

**Comment by kasapiniz** [comment]
fix-https://github.com/buildwiththeta/theta_studio/pull/135
