### ISSUE TITLE
Bug Report : Invitation Code Counting and User Joining Issue

### ISSUE THREAD

**Issue by ghostyARYAN** [buildwiththeta/buildwiththeta#187]
# **Title:** 

Invitation Code Counting and User Joining Issue

## **Description:** 

When generating an invitation code from the home page of the BuildWithTheta app (https://app.buildwiththeta.com/dash), the code is successfully generated. However, when a user joins using the generated code, the app fails to count the invites correctly. Additionally, the invitation link disappears and the user's join status is not updated.

---

## **Flutter Environment:** 

NA

## **App Version:** 

0.3

## **Device Information:** 

Chrome on Windows

---

## **Steps to Reproduce:** 

1.Open the BuildWithTheta app.
2.Navigate to the home page (https://app.buildwiththeta.com/dash).
3.Locate the "Invitation Codes" section on the home page.
4.Generate an invitation code by clicking the "Generate Code" button.
5.Share the generated invitation code with a user.
6.Instruct the user to open the app and navigate to the home page.
7.Instruct the user to enter the generated invitation code and join.
8.Verify the invitation code count and user's join status.

## **Expected Behavior:** 

After generating the invitation code, it should be unique and displayed in the "Invitation Codes" section.
When a user joins using the generated code, the app should increment the invitation code count by 1.
The invitation link should remain visible even after a user joins.
The user's join status should be updated to indicate that they have joined successfully.

## **Actual Behavior:** 

The generated invitation code is unique and displayed in the "Invitation Codes" section.
When a user joins using the generated code, the app fails to increment the invitation code count.
The invitation link disappears from the "Invitation Codes" section after a user joins.
The user's join status remains unchanged and does not indicate that they have joined successfully.

## **Logs:** 

N/A

## **Screenshots:**

![screencapture-app-buildwiththeta-dash-2023-07-10-12_51_26](https://github.com/buildwiththeta/buildwiththeta/assets/65958223/07b483f2-3719-4d2e-a0f4-5b6db06b4ce2).

## **Additional Context:** 

N/A

## **Possible Solution:** 

It is recommended to check the backend implementation of the invitation code tracking and user joining functionality. Verify that the appropriate API endpoints are being called and the database is updated correctly. Additionally, ensure that the frontend UI is correctly displaying the invitation code count and the user's join status.

---

**Comment by andreabuttarelli** [comment]
Thank you for your issues! I fixed the joined people count this morning.
