### ISSUE TITLE
[Bug]: Color crashes 

### ISSUE THREAD

**Issue by thunderstorms-plus** [buildwiththeta/buildwiththeta#188]
Hello 
1. I caught when changing the color of container and caught a bug

Samsung Tab s6 lite | android 13

![IMG_20230710_224438_901](https://github.com/buildwiththeta/buildwiththeta/assets/30003442/7c6fc76d-9ecb-4337-95e2-d3e943d25a4a)

**Comment by thunderstorms-plus** [comment]
Brower chrome 114.0.5735.196

**Comment by andreabuttarelli** [comment]
At the moment, we will focus only on desktop browsers on macOS and Windows.
