### ISSUE TITLE
[Bug]: Visibility doesn’t work for Containers

### ISSUE THREAD

**Issue by andreabuttarelli** [buildwiththeta/buildwiththeta#194]
### Product

Theta Studio

### Bug

Looks like visibility checks are skipped for Containers

### Code of Conduct

- [X] I agree to follow the Code of Conduct for this project.

**Comment by ghostyARYAN** [comment]
Video - https://cdn.discordapp.com/attachments/1118850261868347495/1129409326503694385/screen-capture_1.mp4
