### ISSUE TITLE
Clicking on UI item and then on left menu makes web app stuck

### ISSUE THREAD

**Issue by spioc999** [buildwiththeta/buildwiththeta#65]
# **Title:** 

Clicking on UI item and then on left menu makes web app stuck

## **Description:** 

Every time you click on UI item (e.g. for changing properties) and then you click on one of following three menu element, the web app got stuck
<img width="105" alt="Screenshot 2023-05-31 at 23 18 44" src="https://github.com/buildwiththeta/buildwiththeta/assets/52169960/a638324e-36d3-40b9-9a17-03eddf60d18b">

---

## **Flutter Environment:** 

[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale
    en-IT)
    • Flutter version 3.10.2 on channel stable at
      /Users/spioc/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

## **App Version:** 

N/A

## **Device Information:** 

-

---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1.  Open Theta web app
2. On any page, add a Container
3. Click on it
4. Then click on one of those three
<img width="105" alt="Screenshot 2023-05-31 at 23 18 44" src="https://github.com/buildwiththeta/buildwiththeta/assets/52169960/5db8f20e-f03c-49d6-99aa-6a7853919dfe">

## **Expected Behavior:** 

Not getting stuck

## **Actual Behavior:** 

Web app stops working and the page doesn't respond anymore.

## **Logs:** 

Run `flutter run` or `flutter build` and paste any error logs that might help understand the issue. If the error log is too long, consider using a service like Gist to provide the link to the log.

## **Screenshots:**

If applicable, add screenshots to help explain your problem. Screenshots can be extremely helpful for understanding the issue, especially in the context of visual bugs.

## **Additional Context:** 

Add any other context about the problem here. This could include any relevant configuration, add-ons or libraries used, or other details that might help the developers understand the issue.

## **Possible Solution:** 

If you have an idea of a potential solution, describe it here. If not, feel free to skip this part.

---

Remember, providing as much detail as possible will make it easier for others to help you resolve the bug. If the bug is not immediately reproducible, it may be necessary to provide more context or a sample code snippet that demonstrates the issue.

**Comment by andreabuttarelli** [comment]
A hard fix for this problem has just been distributed.
