### ISSUE TITLE
Container with width and height values not working properly when adding a second container

### ISSUE THREAD

**Issue by kasapiniz** [buildwiththeta/buildwiththeta#78]
# **Title:** 

Container with width and height values not working properly when adding a second container

## **Description:** 

I'm encountering an issue where the width and height values of a Container are not functioning as expected when I add a second Container inside it. The width and height properties of the second Container do not render according to the specified values.And default width and height return 0. Actually the container doesn't seem to use the with and height values ​​at all. It's using Rect(height-with) values.
---

## **Flutter Environment:** 

Provide information about your Flutter environment by running the command `flutter doctor -v` and pasting the output here.

## **App Version:** 

Which version of the app does this issue affect? If not applicable, write "N/A" or "Not applicable".

## **Device Information:** 

Please provide information about the device on which you're experiencing this issue (e.g., manufacturer, model, OS version).

---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. Add a Container 
2. Add a second Container as a child of the first Container. 
3. Set the width and height properties of the second Container with specific values.

## **Expected Behavior:** 

I expected both the first Container and the second Container to render with the specified width and height values. The second Container should respect the provided dimensions.

## **Actual Behavior:** 

Instead of the expected behavior, the second Container does not render with the specified width and height values. It seems to ignore these properties and takes up the default dimensions.

## **Logs:** 

Run `flutter run` or `flutter build` and paste any error logs that might help understand the issue. If the error log is too long, consider using a service like Gist to provide the link to the log.

## **Screenshots:**

If applicable, add screenshots to help explain your problem. Screenshots can be extremely helpful for understanding the issue, especially in the context of visual bugs.

## **Additional Context:** 

Add any other context about the problem here. This could include any relevant configuration, add-ons or libraries used, or other details that might help the developers understand the issue.

## **Possible Solution:** 

If you have an idea of a potential solution, describe it here. If not, feel free to skip this part.

---

Remember, providing as much detail as possible will make it easier for others to help you resolve the bug. If the bug is not immediately reproducible, it may be necessary to provide more context or a sample code snippet that demonstrates the issue.

**Comment by andreabuttarelli** [comment]
I believe this is the normal behavior of containers in Flutter. To override it, wrap the second container inside an Align.
